name: Docker Image CI

env:
  docker_image: duchenpaul/404-page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.docker_image }}:${GITHUB_SHA::8}
      
    - name: Docker Push
      run: docker push ${{ env.docker_image }}:${GITHUB_SHA::8}

    - name: Update the latest image
      run: docker tag ${{ env.docker_image }}:${GITHUB_SHA::8} --tag ${{ env.docker_image }}:latest

    - name: Docker push the latest image
      run: docker push ${{ env.docker_image }}:latest
